#!/usr/bin/env bash
set -euo pipefail

# provision-profile.sh - SharePoint Profile Provisioning Wizard
#
# Interactive wizard to create and configure a SharePoint browser profile
# for use with this skill. Profiles are stored within the skill directory.

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
PROFILE_DIR="$SKILL_DIR/profile"
CONFIG_FILE="$SKILL_DIR/.config"

# Print header
print_header() {
  echo ""
  echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${BLUE}║${NC}  SharePoint/OneDrive Profile Provisioning Wizard         ${BLUE}║${NC}"
  echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
  echo ""
}

# Print step
print_step() {
  local step="$1"
  local total="$2"
  local title="$3"
  echo ""
  echo -e "${YELLOW}▶ Step $step/$total: $title${NC}"
  echo ""
}

# Check if profile already exists
check_existing_profile() {
  if [[ -d "$PROFILE_DIR" ]] && [[ -f "$CONFIG_FILE" ]]; then
    echo -e "${YELLOW}⚠ Existing profile detected${NC}"
    echo ""
    echo "Profile location: $PROFILE_DIR"
    echo "Configuration: $CONFIG_FILE"
    echo ""

    # Load existing config
    source "$CONFIG_FILE"
    echo "Current configuration:"
    echo "  Tenant URL: ${SP_TENANT_URL:-not set}"
    echo "  User Path: ${SP_USER_PATH:-not set}"
    echo ""

    read -p "Do you want to re-provision (this will overwrite)? [y/N] " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      echo "Keeping existing profile. Exiting."
      exit 0
    fi

    echo -e "${YELLOW}Cleaning up existing profile...${NC}"
    pkill -9 -f "$PROFILE_DIR" 2>/dev/null || true
    rm -rf "$PROFILE_DIR"
    rm -f "$CONFIG_FILE"
    sleep 1
  fi
}

# Prompt for SharePoint site URL
prompt_site_url() {
  echo "Enter your SharePoint site URL:"
  echo ""
  echo "This is the URL you use to access SharePoint in your browser."
  echo ""
  echo "Examples:"
  echo "  Commercial:   https://contoso.sharepoint.com"
  echo "  GCC High:     https://agency.sharepoint.us"
  echo "  Personal:     https://contoso-my.sharepoint.com"
  echo "  Site:         https://contoso.sharepoint.com/sites/teamsite"
  echo ""
  read -p "SharePoint URL: " SP_TENANT_URL

  # Validate URL format
  if [[ ! "$SP_TENANT_URL" =~ ^https:// ]]; then
    echo -e "${RED}Error: URL must start with https://${NC}"
    exit 1
  fi

  # Detect tenant type from URL
  if [[ "$SP_TENANT_URL" =~ \.sharepoint\.us ]]; then
    TENANT_TYPE="gcc-high"
    USER_SUFFIX="_onmicrosoft_us"
  elif [[ "$SP_TENANT_URL" =~ \.sharepoint\.com ]]; then
    TENANT_TYPE="commercial"
    USER_SUFFIX="_com"
  else
    TENANT_TYPE="custom"
    USER_SUFFIX=""
  fi

  echo -e "${GREEN}✓ Site URL: $SP_TENANT_URL${NC}"
  echo -e "${GREEN}✓ Detected type: $TENANT_TYPE${NC}"
}

# Prompt for username
prompt_username() {
  echo "Enter your Microsoft 365 username (email):"
  echo ""
  echo "This is the email address you use to sign into SharePoint."
  echo ""
  echo "Example: john.smith@contoso.com"
  echo ""
  read -p "Username: " USER_EMAIL

  if [[ ! "$USER_EMAIL" =~ @ ]]; then
    echo -e "${RED}Error: Username should be a valid email address${NC}"
    exit 1
  fi

  # Extract username part (before @)
  local username=$(echo "$USER_EMAIL" | cut -d'@' -f1 | tr '.' '_')

  # Extract domain from SharePoint URL
  local tenant_name=$(echo "$SP_TENANT_URL" | sed 's|https://||' | sed 's|-my\.sharepoint.*||' | sed 's|\.sharepoint.*||')

  # Build user path based on site type
  if [[ "$SP_TENANT_URL" =~ -my\.sharepoint ]]; then
    # Personal OneDrive site - extract from URL
    SP_USER_PATH=$(echo "$SP_TENANT_URL" | sed 's|https://[^/]*/||' | sed 's|/$||')
    if [[ -z "$SP_USER_PATH" ]]; then
      # If no path in URL, construct from username
      SP_USER_PATH="/personal/${username}_${tenant_name}${USER_SUFFIX}"
    fi
  else
    # Regular site or tenant root - construct personal path
    SP_USER_PATH="/personal/${username}_${tenant_name}${USER_SUFFIX}"
  fi

  echo -e "${GREEN}✓ Username: $USER_EMAIL${NC}"
  echo -e "${GREEN}✓ User path: $SP_USER_PATH${NC}"
}

# Save configuration
save_configuration() {
  cat > "$CONFIG_FILE" <<EOF
# SharePoint API Skill Configuration
# Auto-generated by provision-profile.sh
# Created: $(date)

# SharePoint site
export SP_TENANT_URL="$SP_TENANT_URL"
export SP_USER_PATH="$SP_USER_PATH"
export SP_TENANT_TYPE="$TENANT_TYPE"
export SP_USER_EMAIL="$USER_EMAIL"

# Profile location (relative to skill directory)
export SP_PROFILE_PATH="$PROFILE_DIR"

# Session prefix for agent-browser
export SP_SESSION_PREFIX="sharepoint"

# RenderListDataAsStream options
export SP_RENDER_OPTIONS="5691143"
EOF

  chmod 600 "$CONFIG_FILE"
  echo -e "${GREEN}✓ Configuration saved: $CONFIG_FILE${NC}"
}

# Create profile directory
create_profile_dir() {
  mkdir -p "$PROFILE_DIR"
  chmod 700 "$PROFILE_DIR"
  echo -e "${GREEN}✓ Profile directory created: $PROFILE_DIR${NC}"
}

# Authenticate browser
authenticate_browser() {
  echo ""
  echo -e "${YELLOW}Opening browser for authentication...${NC}"
  echo ""
  echo "Please complete the following steps in the browser:"
  echo ""
  echo "  1. Sign in with your username: ${BLUE}$USER_EMAIL${NC}"
  echo "  2. Enter your password"
  echo "  3. Complete MFA if required (Duo, Authenticator, etc.)"
  echo "  4. Verify you can access SharePoint"
  echo "  5. Close the browser window or press Ctrl+C here when done"
  echo ""
  echo "The browser will open to:"
  echo "  $SP_TENANT_URL"
  echo ""
  echo -e "${YELLOW}Press Enter to open browser...${NC}"
  read -r

  # Open browser with profile
  agent-browser --profile "$PROFILE_DIR" open "$SP_TENANT_URL" || {
    echo -e "${RED}Error: Failed to open browser${NC}" >&2
    echo "Is agent-browser installed? Try: npm install -g agent-browser" >&2
    exit 1
  }

  echo ""
  echo -e "${GREEN}✓ Browser authentication complete${NC}"
}

# Test profile
test_profile() {
  echo ""
  echo "Testing profile authentication..."

  # Load config
  source "$CONFIG_FILE"

  # Create test session
  local session_id
  session_id="$(agent-browser session id --scope worktree --prefix test-provision 2>/dev/null || echo "")"

  if [[ -z "$session_id" ]]; then
    echo -e "${RED}Error: Failed to create test session${NC}" >&2
    exit 1
  fi

  export AGENT_BROWSER_SESSION="$session_id"

  # Test authentication
  local test_result
  test_result=$(cat <<'SCRIPT' | agent-browser --session "$session_id" --profile "$SP_PROFILE_PATH" eval --stdin 2>&1 || echo "error"
(async () => {
  try {
    const response = await fetch(process.env.SP_TENANT_URL, { method: 'HEAD' });
    return JSON.stringify({ ok: response.ok, status: response.status });
  } catch (e) {
    return JSON.stringify({ ok: false, error: e.message });
  }
})();
SCRIPT
)

  # Close test session
  agent-browser --session "$session_id" close 2>/dev/null || true

  # Check result
  if echo "$test_result" | jq -e '.ok == true' >/dev/null 2>&1; then
    echo -e "${GREEN}✓ Profile test successful${NC}"
    return 0
  else
    echo -e "${RED}⚠ Profile test failed${NC}"
    echo "Response: $test_result"
    echo ""
    echo "This might be normal if authentication is still pending."
    echo "Try running: bash scripts/session-manager.sh status"
    return 1
  fi
}

# Print completion summary
print_completion() {
  echo ""
  echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
  echo -e "${GREEN}║${NC}  Profile Provisioning Complete!                           ${GREEN}║${NC}"
  echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
  echo ""
  echo "Profile location:"
  echo "  $PROFILE_DIR"
  echo ""
  echo "Configuration:"
  echo "  $CONFIG_FILE"
  echo ""
  echo "Next steps:"
  echo ""
  echo "  1. Load configuration:"
  echo "     source $CONFIG_FILE"
  echo ""
  echo "  2. Create session:"
  echo "     bash scripts/session-manager.sh create"
  echo ""
  echo "  3. List files:"
  echo "     bash scripts/list-files.sh"
  echo ""
  echo -e "${YELLOW}Note: Configuration is automatically loaded by scripts${NC}"
  echo ""
}

# Main wizard flow
main() {
  print_header

  # Check agent-browser
  if ! command -v agent-browser >/dev/null 2>&1; then
    echo -e "${RED}Error: agent-browser not found${NC}" >&2
    echo "" >&2
    echo "Install with:" >&2
    echo "  npm install -g agent-browser" >&2
    echo "  or" >&2
    echo "  brew install agent-browser" >&2
    exit 1
  fi

  # Check existing profile
  check_existing_profile

  # Step 1: SharePoint URL
  print_step 1 4 "SharePoint Site URL"
  prompt_site_url

  # Step 2: Username
  print_step 2 4 "Microsoft 365 Username"
  prompt_username

  # Step 3: Create profile
  print_step 3 4 "Create Profile Directory"
  create_profile_dir
  save_configuration

  # Step 4: Authenticate
  print_step 4 4 "Authenticate Browser"
  authenticate_browser

  # Test (optional, non-blocking)
  test_profile || true

  # Done
  print_completion
}

main "$@"
